[build]
  command = "apt-get install -y libpq-dev && pip install -r requirements.txt && python app.py"
  publish = "public"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/app.py"
  status = 200
