[build]
  command = "whoami && pip cache purge && pip install psycopg2-binary==2.9.10 && pip install -r requirements.txt  && python app.py"
  publish = "public"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/app.py"
  status = 200
