[build]
  command = "apt-get install libpq-dev python3-dev postgresql-server-dev-all && pip install -r requirements.txt && python app.py"
  publish = "public"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/app.py"
  status = 200
