[build]
  command = "pip install psycopg2-binary==2.9.10 && pip install -r requirements.txt "
  publish = "public"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/app.py"
  status = 200
